### ISSUE TITLE
Hyperlinks causes RG and Guilded to stop loading

### ISSUE THREAD

**Issue by ny404** [ReGuilded/ReGuilded#27] opened 2022-01-14 19:19 UTC
Please see attached video!

https://user-images.githubusercontent.com/38796514/149572651-0973f7db-5d84-4371-936a-11715ab19083.mp4

**Comment by ItzNxthaniel** [comment] 2022-01-14 20:01
We've found an error relating to this issue, and will look into this:
`"Render frame was disposed before WebFrameMain could be accessed"`

**Comment by IdkGoodName** [comment] 2022-01-16 17:51
Fixed with commit e8f39ef.

**Comment by ItzNxthaniel** [comment] 2022-01-17 20:26
Confirmed to still be broke.

**Comment by ItzNxthaniel** [comment] 2022-01-25 22:41
Okay, we're pretty sure this issue has been fixed, and the issue was still present due to a local repo mishap.

**Closed by ItzNxthaniel** 2022-01-25 22:41 UTC
Labels: Bug
